function graph_3d
close all
clc
global GUI;

GUI.h = figure('units', 'pixels',...
    'position', [10 300 1000 500],...
    'menubar','none',...
    'name','Graph 3D',...
    'numbertitle', 'off',...
    'resize', 'off',...
    'Color','white');

% ..................................................................x input
% x = -3:0.2:3;
GUI.x_input_title = uicontrol('Parent', GUI.h,...
    'Style', 'Text',...
    'String','Input for X:',...
    'Position',[120 155 125 22],...
    'Fontsize', 14,...
    'FontWeight', 'bold',...
    'visible', 'on',...
    'BackgroundColor','black');

GUI.x_start = uicontrol('Parent', GUI.h,...
    'Style', 'Text',...
    'String','Start:',...
    'Position',[130 155 125 22],...
    'Fontsize', 14,...
    'FontWeight', 'bold',...
    'visible', 'on',...
    'BackgroundColor','black');

GUI.x_start_var = uicontrol('Parent', GUI.h,...
    'Style', 'edit',...
    'Position',[140 155 100 22],...
    'Fontsize', 14,...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'center',...
    'string', '-3',...
    'BackgroundColor','white');

% GUI.x_step = uicontrol('Parent', GUI.h,...
%     'Style', 'Text',...
%     'String','Step:',...
%     'Position',[15 145 125 22],...
%     'Fontsize', 14,...
%     'FontWeight', 'bold',...
%     'visible', 'on',...
%     'BackgroundColor','white');
% 
% GUI.x_step_var = uicontrol('Parent', GUI.h,...
%     'Style', 'edit',...
%     'Position',[25 145 125 22],...
%     'Fontsize', 14,...
%     'FontWeight', 'bold',...
%     'HorizontalAlignment', 'center',...
%     'string', '0.2',...
%     'BackgroundColor','white');
% 
% GUI.x_end = uicontrol('Parent', GUI.h,...
%     'Style', 'Text',...
%     'String','End:',...
%     'Position',[15 135 125 22],...
%     'Fontsize', 14,...
%     'FontWeight', 'bold',...
%     'visible', 'on',...
%     'BackgroundColor','white');
% 
% GUI.x_end_var = uicontrol('Parent', GUI.h,...
%     'Style', 'edit',...
%     'Position',[25 135 125 22],...
%     'Fontsize', 14,...
%     'FontWeight', 'bold',...
%     'HorizontalAlignment', 'center',...
%     'string', '3',...
%     'BackgroundColor','white');



end